/** @type {import('tailwindcss').Config} */
const config = {
  theme: {
    extend: {
      colors: {
        bg: {
          base: {
            primary: 'var(--colors-bg-base-primary)',
            secondary: 'var(--colors-bg-base-secondary)',
            tertiary: 'var(--colors-bg-base-tertiary)',
            quaternary: 'var(--colors-bg-base-quaternary)',
            'brand-primary-tint': 'var(--colors-bg-base-brand-primary-tint)',
            'brand-secondary-tint': 'var(--colors-bg-base-brand-secondary-tint)',
            'brand-tertiary-tint': 'var(--colors-bg-base-brand-tertiary-tint)',
            'brand-quaternary-tint': 'var(--colors-bg-base-brand-quaternary-tint)',
            'brand-quinary-tint': 'var(--colors-bg-base-brand-quinary-tint)',
            'brand-senary-tint': 'var(--colors-bg-base-brand-senary-tint)',
            'brand-primary': 'var(--colors-bg-base-brand-primary)',
            'brand-tertiary': 'var(--colors-bg-base-brand-tertiary)',
            'brand-quarternary': 'var(--colors-bg-base-brand-quarternary)',
            success: 'var(--colors-bg-base-success)',
            warning: 'var(--colors-bg-base-warning)',
            destructive: 'var(--colors-bg-base-destructive)',
            information: 'var(--colors-bg-base-information)',
            'alpha-overlay': 'var(--colors-bg-base-alpha-overlay)',
            'alpha-none': 'var(--colors-bg-base-alpha-none)',
            'alpha-low': 'var(--colors-bg-base-alpha-low)',
            'alpha-medium': 'var(--colors-bg-base-alpha-medium)',
            'alpha-high': 'var(--colors-bg-base-alpha-high)',
          },
          badge: {
            primary: {
              hover: 'var(--colors-bg-badge-primary-hover)',
              default: 'var(--colors-bg-badge-primary-default)',
            },
            secondary: {
              hover: 'var(--colors-bg-badge-secondary-hover)',
              default: 'var(--colors-bg-badge-secondary-default)',
            },
            tertiary: {
              hover: 'var(--colors-bg-badge-tertiary-hover)',
              default: 'var(--colors-bg-badge-tertiary-default)',
            },
            outline: {
              hover: 'var(--colors-bg-badge-outline-hover)',
              default: 'var(--colors-bg-badge-outline-default)',
            },
          },
          button: {
            primary: {
              hover: 'var(--colors-bg-button-primary-hover)',
              active: 'var(--colors-bg-button-primary-active)',
              disabled: 'var(--colors-bg-button-primary-disabled)',
              default: 'var(--colors-bg-button-primary-default)',
            },
            secondary: {
              hover: 'var(--colors-bg-button-secondary-hover)',
              active: 'var(--colors-bg-button-secondary-active)',
              disabled: 'var(--colors-bg-button-secondary-disabled)',
              default: 'var(--colors-bg-button-secondary-default)',
            },
            tertiary: {
              hover: 'var(--colors-bg-button-tertiary-hover)',
              active: 'var(--colors-bg-button-tertiary-active)',
              disabled: 'var(--colors-bg-button-tertiary-disabled)',
              default: 'var(--colors-bg-button-tertiary-default)',
            },
          },
          dataviz: {
            'dataviz-1': 'var(--colors-bg-dataviz-dataviz-1)',
            'dataviz-2': 'var(--colors-bg-dataviz-dataviz-2)',
            'dataviz-3': 'var(--colors-bg-dataviz-dataviz-3)',
            'dataviz-4': 'var(--colors-bg-dataviz-dataviz-4)',
            'dataviz-5': 'var(--colors-bg-dataviz-dataviz-5)',
            map: {
              state: 'var(--colors-bg-dataviz-map-state)',
              'state-level-1': 'var(--colors-bg-dataviz-map-state-level-1)',
              'state-level-2': 'var(--colors-bg-dataviz-map-state-level-2)',
              'state-level-3': 'var(--colors-bg-dataviz-map-state-level-3)',
              'state-level-4': 'var(--colors-bg-dataviz-map-state-level-4)',
              'state-level-5': 'var(--colors-bg-dataviz-map-state-level-5)',
            },
            'dataviz-6': 'var(--colors-bg-dataviz-dataviz-6)',
          },
          footer: { default: 'var(--colors-bg-footer-default)' },
          input: {
            focus: 'var(--colors-bg-input-focus)',
            hover: 'var(--colors-bg-input-hover)',
            disabled: 'var(--colors-bg-input-disabled)',
            default: 'var(--colors-bg-input-default)',
          },
          jumpnav: { default: 'var(--colors-bg-jumpnav-default)' },
          link: {
            filled: {
              visited: 'var(--colors-bg-link-filled-visited)',
              hover: 'var(--colors-bg-link-filled-hover)',
              active: 'var(--colors-bg-link-filled-active)',
              default: 'var(--colors-bg-link-filled-default)',
            },
          },
          logo: {
            box: 'var(--colors-bg-logo-box)',
            'dog-ear': 'var(--colors-bg-logo-dog-ear)',
            'word-on-box': 'var(--colors-bg-logo-word-on-box)',
            'word-name': 'var(--colors-bg-logo-word-name)',
          },
          menu: {
            hover: 'var(--colors-bg-menu-hover)',
            active: 'var(--colors-bg-menu-active)',
            selected: 'var(--colors-bg-menu-selected)',
            default: 'var(--colors-bg-menu-default)',
          },
          navigation: {
            hover: 'var(--colors-bg-navigation-hover)',
            active: 'var(--colors-bg-navigation-active)',
            selected: 'var(--colors-bg-navigation-selected)',
            expanded: 'var(--colors-bg-navigation-expanded)',
            default: 'var(--colors-bg-navigation-default)',
          },
          pagination: {
            hover: 'var(--colors-bg-pagination-hover)',
            active: 'var(--colors-bg-pagination-active)',
            selected: 'var(--colors-bg-pagination-selected)',
            default: 'var(--colors-bg-pagination-default)',
          },
          slider: {
            active: 'var(--colors-bg-slider-active)',
            default: 'var(--colors-bg-slider-default)',
          },
          'sonner-button': {
            hover: 'var(--colors-bg-sonner-button-hover)',
            active: 'var(--colors-bg-sonner-button-active)',
            default: 'var(--colors-bg-sonner-button-default)',
          },
          'spotify-player': { primary: 'var(--colors-bg-spotify-player-primary)' },
          switch: {
            selected: 'var(--colors-bg-switch-selected)',
            default: 'var(--colors-bg-switch-default)',
          },
          tabs: {
            hover: 'var(--colors-bg-tabs-hover)',
            active: 'var(--colors-bg-tabs-active)',
            selected: 'var(--colors-bg-tabs-selected)',
            default: 'var(--colors-bg-tabs-default)',
          },
          'toast-button': {
            base: {
              hover: 'var(--colors-bg-toast-button-base-hover)',
              active: 'var(--colors-bg-toast-button-base-active)',
              default: 'var(--colors-bg-toast-button-base-default)',
            },
            destructive: {
              hover: 'var(--colors-bg-toast-button-destructive-hover)',
              active: 'var(--colors-bg-toast-button-destructive-active)',
              default: 'var(--colors-bg-toast-button-destructive-default)',
            },
          },
          toggle: {
            hover: 'var(--colors-bg-toggle-hover)',
            active: 'var(--colors-bg-toggle-active)',
            selected: 'var(--colors-bg-toggle-selected)',
            disabled: 'var(--colors-bg-toggle-disabled)',
            default: 'var(--colors-bg-toggle-default)',
          },
        },
        text: {
          base: {
            primary: 'var(--colors-text-base-primary)',
            secondary: 'var(--colors-text-base-secondary)',
            tertiary: 'var(--colors-text-base-tertiary)',
            quaternary: 'var(--colors-text-base-quaternary)',
            'brand-primary': 'var(--colors-text-base-brand-primary)',
            'brand-secondary': 'var(--colors-text-base-brand-secondary)',
            'brand-tertiary': 'var(--colors-text-base-brand-tertiary)',
            'brand-quaternary': 'var(--colors-text-base-brand-quaternary)',
            'title-brand-quarternary': 'var(--colors-text-base-title-brand-quarternary)',
            success: 'var(--colors-text-base-success)',
            warning: 'var(--colors-text-base-warning)',
            destructive: 'var(--colors-text-base-destructive)',
            information: 'var(--colors-text-base-information)',
          },
          icon: {
            primary: 'var(--colors-text-icon-primary)',
            secondary: 'var(--colors-text-icon-secondary)',
            tertiary: 'var(--colors-text-icon-tertiary)',
            quaternary: 'var(--colors-text-icon-quaternary)',
            'brand-primary': 'var(--colors-text-icon-brand-primary)',
            'brand-secondary': 'var(--colors-text-icon-brand-secondary)',
            'brand-tertiary': 'var(--colors-text-icon-brand-tertiary)',
            'brand-quaternary': 'var(--colors-text-icon-brand-quaternary)',
            success: 'var(--colors-text-icon-success)',
            warning: 'var(--colors-text-icon-warning)',
            destructive: 'var(--colors-text-icon-destructive)',
            information: 'var(--colors-text-icon-information)',
          },
          badge: {
            primary: {
              base: {
                hover: 'var(--colors-text-badge-primary-base-hover)',
                default: 'var(--colors-text-badge-primary-base-default)',
              },
              icon: {
                hover: 'var(--colors-text-badge-primary-icon-hover)',
                default: 'var(--colors-text-badge-primary-icon-default)',
              },
            },
            secondary: {
              base: {
                hover: 'var(--colors-text-badge-secondary-base-hover)',
                default: 'var(--colors-text-badge-secondary-base-default)',
              },
              icon: {
                hover: 'var(--colors-text-badge-secondary-icon-hover)',
                default: 'var(--colors-text-badge-secondary-icon-default)',
              },
            },
            tertiary: {
              base: {
                hover: 'var(--colors-text-badge-tertiary-base-hover)',
                default: 'var(--colors-text-badge-tertiary-base-default)',
              },
              icon: {
                hover: 'var(--colors-text-badge-tertiary-icon-hover)',
                default: 'var(--colors-text-badge-tertiary-icon-default)',
              },
            },
            outline: {
              base: {
                hover: 'var(--colors-text-badge-outline-base-hover)',
                default: 'var(--colors-text-badge-outline-base-default)',
              },
              icon: {
                hover: 'var(--colors-text-badge-outline-icon-hover)',
                default: 'var(--colors-text-badge-outline-icon-default)',
              },
            },
          },
          button: {
            primary: {
              base: {
                hover: 'var(--colors-text-button-primary-base-hover)',
                active: 'var(--colors-text-button-primary-base-active)',
                disabled: 'var(--colors-text-button-primary-base-disabled)',
                default: 'var(--colors-text-button-primary-base-default)',
              },
              icon: {
                hover: 'var(--colors-text-button-primary-icon-hover)',
                active: 'var(--colors-text-button-primary-icon-active)',
                disabled: 'var(--colors-text-button-primary-icon-disabled)',
                default: 'var(--colors-text-button-primary-icon-default)',
              },
            },
            secondary: {
              base: {
                hover: 'var(--colors-text-button-secondary-base-hover)',
                active: 'var(--colors-text-button-secondary-base-active)',
                disabled: 'var(--colors-text-button-secondary-base-disabled)',
                default: 'var(--colors-text-button-secondary-base-default)',
              },
              icon: {
                hover: 'var(--colors-text-button-secondary-icon-hover)',
                active: 'var(--colors-text-button-secondary-icon-active)',
                disabled: 'var(--colors-text-button-secondary-icon-disabled)',
                default: 'var(--colors-text-button-secondary-icon-default)',
              },
            },
            tertiary: {
              base: {
                hover: 'var(--colors-text-button-tertiary-base-hover)',
                active: 'var(--colors-text-button-tertiary-base-active)',
                disabled: 'var(--colors-text-button-tertiary-base-disabled)',
                default: 'var(--colors-text-button-tertiary-base-default)',
              },
              icon: {
                hover: 'var(--colors-text-button-tertiary-icon-hover)',
                active: 'var(--colors-text-button-tertiary-icon-active)',
                disabled: 'var(--colors-text-button-tertiary-icon-disabled)',
                default: 'var(--colors-text-button-tertiary-icon-default)',
              },
            },
          },
          dataviz: {
            'dataviz-1': 'var(--colors-text-dataviz-dataviz-1)',
            'dataviz-2': 'var(--colors-text-dataviz-dataviz-2)',
            'dataviz-3': 'var(--colors-text-dataviz-dataviz-3)',
            'dataviz-4': 'var(--colors-text-dataviz-dataviz-4)',
            'dataviz-5': 'var(--colors-text-dataviz-dataviz-5)',
            'map-state-label': 'var(--colors-text-dataviz-map-state-label)',
            'map-state-label-outside': 'var(--colors-text-dataviz-map-state-label-outside)',
          },
          input: {
            base: {
              placeholder: 'var(--colors-text-input-base-placeholder)',
              hover: 'var(--colors-text-input-base-hover)',
              focus: 'var(--colors-text-input-base-focus)',
              selected: 'var(--colors-text-input-base-selected)',
              disabled: 'var(--colors-text-input-base-disabled)',
              default: 'var(--colors-text-input-base-default)',
            },
            icon: {
              placeholder: 'var(--colors-text-input-icon-placeholder)',
              hover: 'var(--colors-text-input-icon-hover)',
              focus: 'var(--colors-text-input-icon-focus)',
              'selected-alt': 'var(--colors-text-input-icon-selected-alt)',
              disabled: 'var(--colors-text-input-icon-disabled)',
              default: 'var(--colors-text-input-icon-default)',
            },
          },
          link: {
            filled: {
              base: {
                visited: 'var(--colors-text-link-filled-base-visited)',
                hover: 'var(--colors-text-link-filled-base-hover)',
                active: 'var(--colors-text-link-filled-base-active)',
                default: 'var(--colors-text-link-filled-base-default)',
              },
              icon: {
                visited: 'var(--colors-text-link-filled-icon-visited)',
                hover: 'var(--colors-text-link-filled-icon-hover)',
                active: 'var(--colors-text-link-filled-icon-active)',
                default: 'var(--colors-text-link-filled-icon-default)',
              },
            },
            footer: {
              base: {
                visited: 'var(--colors-text-link-footer-base-visited)',
                hover: 'var(--colors-text-link-footer-base-hover)',
                active: 'var(--colors-text-link-footer-base-active)',
                default: 'var(--colors-text-link-footer-base-default)',
              },
            },
            nav: {
              base: {
                visited: 'var(--colors-text-link-nav-base-visited)',
                hover: 'var(--colors-text-link-nav-base-hover)',
                active: 'var(--colors-text-link-nav-base-active)',
                default: 'var(--colors-text-link-nav-base-default)',
              },
            },
            default: {
              base: {
                default: 'var(--colors-text-link-default-base-default)',
                visited: 'var(--colors-text-link-default-base-visited)',
                hover: 'var(--colors-text-link-default-base-hover)',
                active: 'var(--colors-text-link-default-base-active)',
              },
              icon: {
                default: 'var(--colors-text-link-default-icon-default)',
                visited: 'var(--colors-text-link-default-icon-visited)',
                hover: 'var(--colors-text-link-default-icon-hover)',
                active: 'var(--colors-text-link-default-icon-active)',
              },
            },
          },
          menu: {
            base: {
              hover: 'var(--colors-text-menu-base-hover)',
              active: 'var(--colors-text-menu-base-active)',
              selected: 'var(--colors-text-menu-base-selected)',
              default: 'var(--colors-text-menu-base-default)',
            },
          },
          navigation: {
            base: {
              featured: 'var(--colors-text-navigation-base-featured)',
              hover: 'var(--colors-text-navigation-base-hover)',
              active: 'var(--colors-text-navigation-base-active)',
              default: 'var(--colors-text-navigation-base-default)',
            },
            icon: {
              featured: 'var(--colors-text-navigation-icon-featured)',
              hover: 'var(--colors-text-navigation-icon-hover)',
              active: 'var(--colors-text-navigation-icon-active)',
              default: 'var(--colors-text-navigation-icon-default)',
            },
          },
          'navigation-item': {
            base: {
              visited: 'var(--colors-text-navigation-item-base-visited)',
              hover: 'var(--colors-text-navigation-item-base-hover)',
              active: 'var(--colors-text-navigation-item-base-active)',
              default: 'var(--colors-text-navigation-item-base-default)',
            },
          },
          pagination: {
            base: {
              hover: 'var(--colors-text-pagination-base-hover)',
              active: 'var(--colors-text-pagination-base-active)',
              selected: 'var(--colors-text-pagination-base-selected)',
              default: 'var(--colors-text-pagination-base-default)',
            },
            icon: {
              hover: 'var(--colors-text-pagination-icon-hover)',
              active: 'var(--colors-text-pagination-icon-active)',
              default: 'var(--colors-text-pagination-icon-default)',
            },
          },
          slider: { active: 'var(--colors-text-slider-active)' },
          'sonner-button': {
            base: {
              hover: 'var(--colors-text-sonner-button-base-hover)',
              active: 'var(--colors-text-sonner-button-base-active)',
              default: 'var(--colors-text-sonner-button-base-default)',
            },
          },
          'spotify-player': { primary: 'var(--colors-text-spotify-player-primary)' },
          switch: { default: 'var(--colors-text-switch-default)' },
          tabs: {
            base: {
              hover: 'var(--colors-text-tabs-base-hover)',
              active: 'var(--colors-text-tabs-base-active)',
              selected: 'var(--colors-text-tabs-base-selected)',
              default: 'var(--colors-text-tabs-base-default)',
            },
            icon: {
              hover: 'var(--colors-text-tabs-icon-hover)',
              active: 'var(--colors-text-tabs-icon-active)',
              selected: 'var(--colors-text-tabs-icon-selected)',
              default: 'var(--colors-text-tabs-icon-default)',
            },
          },
          'toast-button': {
            base: {
              hover: 'var(--colors-text-toast-button-base-hover)',
              active: 'var(--colors-text-toast-button-base-active)',
              default: 'var(--colors-text-toast-button-base-default)',
            },
            destructive: {
              hover: 'var(--colors-text-toast-button-destructive-hover)',
              active: 'var(--colors-text-toast-button-destructive-active)',
              default: 'var(--colors-text-toast-button-destructive-default)',
            },
          },
          toggle: {
            base: {
              hover: 'var(--colors-text-toggle-base-hover)',
              active: 'var(--colors-text-toggle-base-active)',
              selected: 'var(--colors-text-toggle-base-selected)',
              disabled: 'var(--colors-text-toggle-base-disabled)',
              default: 'var(--colors-text-toggle-base-default)',
            },
            icon: {
              hover: 'var(--colors-text-toggle-icon-hover)',
              active: 'var(--colors-text-toggle-icon-active)',
              selected: 'var(--colors-text-toggle-icon-selected)',
              disabled: 'var(--colors-text-toggle-icon-disabled)',
              default: 'var(--colors-text-toggle-icon-default)',
            },
          },
          jumpnav: {
            base: {
              hover: 'var(--colors-text-jumpnav-base-hover)',
              active: 'var(--colors-text-jumpnav-base-active)',
              default: 'var(--colors-text-jumpnav-base-default)',
            },
          },
        },
        border: {
          base: {
            primary: 'var(--colors-border-base-primary)',
            secondary: 'var(--colors-border-base-secondary)',
            tertiary: 'var(--colors-border-base-tertiary)',
            quaternary: 'var(--colors-border-base-quaternary)',
            quinary: 'var(--colors-border-base-quinary)',
            'brand-primary': 'var(--colors-border-base-brand-primary)',
            'brand-tertiary': 'var(--colors-border-base-brand-tertiary)',
            'brand-tertiary-tint': 'var(--colors-border-base-brand-tertiary-tint)',
            'brand-quaternary-tint': 'var(--colors-border-base-brand-quaternary-tint)',
            'alpha-none': 'var(--colors-border-base-alpha-none)',
            'alpha-30': 'var(--colors-border-base-alpha-30)',
            success: 'var(--colors-border-base-success)',
            warning: 'var(--colors-border-base-warning)',
            destructive: 'var(--colors-border-base-destructive)',
            information: 'var(--colors-border-base-information)',
          },
          badge: {
            primary: {
              hover: 'var(--colors-border-badge-primary-hover)',
              default: 'var(--colors-border-badge-primary-default)',
            },
            secondary: {
              hover: 'var(--colors-border-badge-secondary-hover)',
              default: 'var(--colors-border-badge-secondary-default)',
            },
            tertiary: {
              hover: 'var(--colors-border-badge-tertiary-hover)',
              default: 'var(--colors-border-badge-tertiary-default)',
            },
            outline: {
              hover: 'var(--colors-border-badge-outline-hover)',
              default: 'var(--colors-border-badge-outline-default)',
            },
          },
          button: {
            primary: {
              hover: 'var(--colors-border-button-primary-hover)',
              active: 'var(--colors-border-button-primary-active)',
              disabled: 'var(--colors-border-button-primary-disabled)',
              default: 'var(--colors-border-button-primary-default)',
            },
            secondary: {
              hover: 'var(--colors-border-button-secondary-hover)',
              active: 'var(--colors-border-button-secondary-active)',
              disabled: 'var(--colors-border-button-secondary-disabled)',
              default: 'var(--colors-border-button-secondary-default)',
            },
            tertiary: {
              hover: 'var(--colors-border-button-tertiary-hover)',
              active: 'var(--colors-border-button-tertiary-active)',
              disabled: 'var(--colors-border-button-tertiary-disabled)',
              default: 'var(--colors-border-button-tertiary-default)',
            },
          },
          dataviz: {
            'dataviz-1': 'var(--colors-border-dataviz-dataviz-1)',
            'dataviz-2': 'var(--colors-border-dataviz-dataviz-2)',
            'dataviz-3': 'var(--colors-border-dataviz-dataviz-3)',
            'dataviz-4': 'var(--colors-border-dataviz-dataviz-4)',
            'dataviz-5': 'var(--colors-border-dataviz-dataviz-5)',
            'map-state': 'var(--colors-border-dataviz-map-state)',
            'map-state-label-stroke': 'var(--colors-border-dataviz-map-state-label-stroke)',
            'map-state-label-line': 'var(--colors-border-dataviz-map-state-label-line)',
          },
          focus: {
            inner: 'var(--colors-border-focus-inner)',
            outer: 'var(--colors-border-focus-outer)',
          },
          input: {
            hover: 'var(--colors-border-input-hover)',
            focus: 'var(--colors-border-input-focus)',
            selected: 'var(--colors-border-input-selected)',
            disabled: 'var(--colors-border-input-disabled)',
            default: 'var(--colors-border-input-default)',
          },
          jumpnav: {
            container: 'var(--colors-border-jumpnav-container)',
            active: 'var(--colors-border-jumpnav-active)',
          },
          link: {
            visited: 'var(--colors-border-link-visited)',
            hover: 'var(--colors-border-link-hover)',
            active: 'var(--colors-border-link-active)',
            default: 'var(--colors-border-link-default)',
          },
          menu: {
            hover: 'var(--colors-border-menu-hover)',
            active: 'var(--colors-border-menu-active)',
            selected: 'var(--colors-border-menu-selected)',
            default: 'var(--colors-border-menu-default)',
          },
          navigation: {
            hover: 'var(--colors-border-navigation-hover)',
            active: 'var(--colors-border-navigation-active)',
            selected: 'var(--colors-border-navigation-selected)',
            expanded: 'var(--colors-border-navigation-expanded)',
            default: 'var(--colors-border-navigation-default)',
          },
          pagination: {
            hover: 'var(--colors-border-pagination-hover)',
            selected: 'var(--colors-border-pagination-selected)',
            default: 'var(--colors-border-pagination-default)',
          },
          select: {
            hover: 'var(--colors-border-select-hover)',
            active: 'var(--colors-border-select-active)',
            disabled: 'var(--colors-border-select-disabled)',
            default: 'var(--colors-border-select-default)',
          },
          slider: { active: 'var(--colors-border-slider-active)' },
          tabs: {
            hover: 'var(--colors-border-tabs-hover)',
            active: 'var(--colors-border-tabs-active)',
            selected: 'var(--colors-border-tabs-selected)',
            default: 'var(--colors-border-tabs-default)',
          },
          'toast-button': {
            base: {
              hover: 'var(--colors-border-toast-button-base-hover)',
              active: 'var(--colors-border-toast-button-base-active)',
              default: 'var(--colors-border-toast-button-base-default)',
            },
            destructive: {
              hover: 'var(--colors-border-toast-button-destructive-hover)',
              active: 'var(--colors-border-toast-button-destructive-active)',
              default: 'var(--colors-border-toast-button-destructive-default)',
            },
          },
          toggle: {
            hover: 'var(--colors-border-toggle-hover)',
            active: 'var(--colors-border-toggle-active)',
            selected: 'var(--colors-border-toggle-selected)',
            disabled: 'var(--colors-border-toggle-disabled)',
            default: 'var(--colors-border-toggle-default)',
          },
          brands: {
            politics: 'var(--color-rc-red-600)',
            crime: 'var(--color-black)',
            religion: 'var(--color-rc-aqua-300)',
            investigations: 'var(--color-rc-gray-650)',
            science: 'var(--color-rc-aqua-800)',
            education: 'var(--color-rc-red-750)',
            history: 'var(--color-rc-orange-500)',
            polling: 'var(--color-rc-gold-100)',
            health: 'var(--color-rc-yellow-250)',
            markets: 'var(--color-rc-green-450)',
            world: 'var(--color-rc-blue-900)',
            policy: 'var(--color-rc-violet-800)',
            defense: 'var(--color-rc-olive-800)',
            pennsylvania: 'var(--color-rc-navy-700)',
            'public-affairs': 'var(--color-rc-green-900)',
            'book-culture': 'var(--color-rc-teal-500)',
          },
        },
      },
      spacing: {
        '0': 'var(--spacing-0)',
        '1': 'var(--spacing-1)',
        '2': 'var(--spacing-2)',
        '3': 'var(--spacing-3)',
        '4': 'var(--spacing-4)',
        '5': 'var(--spacing-5)',
        '6': 'var(--spacing-6)',
        '7': 'var(--spacing-7)',
        '8': 'var(--spacing-8)',
        '9': 'var(--spacing-9)',
        '10': 'var(--spacing-10)',
        '11': 'var(--spacing-11)',
        '12': 'var(--spacing-12)',
        '14': 'var(--spacing-14)',
        '16': 'var(--spacing-16)',
        '20': 'var(--spacing-20)',
        '24': 'var(--spacing-24)',
        '28': 'var(--spacing-28)',
        '32': 'var(--spacing-32)',
        '36': 'var(--spacing-36)',
        '40': 'var(--spacing-40)',
        '44': 'var(--spacing-44)',
        '48': 'var(--spacing-48)',
        '52': 'var(--spacing-52)',
        '56': 'var(--spacing-56)',
        '60': 'var(--spacing-60)',
        '64': 'var(--spacing-64)',
        '72': 'var(--spacing-72)',
        '80': 'var(--spacing-80)',
        '96': 'var(--spacing-96)',
        px: 'var(--spacing-px)',
        '0_5': 'var(--spacing-0-5)',
        '1_5': 'var(--spacing-1-5)',
        '2_5': 'var(--spacing-2-5)',
        '3_5': 'var(--spacing-3-5)',
        '0.5': 'var(--spacing-0-5)',
        '1.5': 'var(--spacing-1-5)',
        '2.5': 'var(--spacing-2-5)',
        '3.5': 'var(--spacing-3-5)',
      },
      fontSize: {
        'display-2xl': 'var(--font-size-display-2xl)',
        'display-xl': 'var(--font-size-display-xl)',
        'display-lg': 'var(--font-size-display-lg)',
        'display-md': 'var(--font-size-display-md)',
        'display-sm': 'var(--font-size-display-sm)',
        'heading-xl': 'var(--font-size-heading-xl)',
        'heading-lg': 'var(--font-size-heading-lg)',
        'heading-md': 'var(--font-size-heading-md)',
        'heading-sm': 'var(--font-size-heading-sm)',
        'heading-xs': 'var(--font-size-heading-xs)',
        'heading-xxs': 'var(--font-size-heading-xxs)',
        'body-xl': 'var(--font-size-body-xl)',
        'body-lg': 'var(--font-size-body-lg)',
        'body-md': 'var(--font-size-body-md)',
        'body-sm': 'var(--font-size-body-sm)',
        'body-xs': 'var(--font-size-body-xs)',
        'label-lg': 'var(--font-size-label-lg)',
        'label-md': 'var(--font-size-label-md)',
        'label-sm': 'var(--font-size-label-sm)',
      },
      lineHeight: {
        'display-2xl': 'var(--line-height-display-2xl)',
        'display-xl': 'var(--line-height-display-xl)',
        'display-lg': 'var(--line-height-display-lg)',
        'display-md': 'var(--line-height-display-md)',
        'display-sm': 'var(--line-height-display-sm)',
        'heading-xl': 'var(--line-height-heading-xl)',
        'heading-lg': 'var(--line-height-heading-lg)',
        'heading-md': 'var(--line-height-heading-md)',
        'heading-sm': 'var(--line-height-heading-sm)',
        'heading-xs': 'var(--line-height-heading-xs)',
        'heading-xxs': 'var(--line-height-heading-xxs)',
        'body-xl': 'var(--line-height-body-xl)',
        'body-lg': 'var(--line-height-body-lg)',
        'body-md': 'var(--line-height-body-md)',
        'body-sm': 'var(--line-height-body-sm)',
        'body-xs': 'var(--line-height-body-xs)',
        'label-lg': 'var(--line-height-label-lg)',
        'label-md': 'var(--line-height-label-md)',
        'label-sm': 'var(--line-height-label-sm)',
      },
      letterSpacing: {
        'display-2xl': 'var(--letter-spacing-display-2xl)',
        'display-xl': 'var(--letter-spacing-display-xl)',
        'display-lg': 'var(--letter-spacing-display-lg)',
        'display-md': 'var(--letter-spacing-display-md)',
        'display-sm': 'var(--letter-spacing-display-sm)',
        'heading-xl': 'var(--letter-spacing-heading-xl)',
        'heading-lg': 'var(--letter-spacing-heading-lg)',
        'heading-md': 'var(--letter-spacing-heading-md)',
        'heading-sm': 'var(--letter-spacing-heading-sm)',
        'heading-xs': 'var(--letter-spacing-heading-xs)',
        'body-xl': 'var(--letter-spacing-body-xl)',
        'body-lg': 'var(--letter-spacing-body-lg)',
        'body-md': 'var(--letter-spacing-body-md)',
        'body-sm': 'var(--letter-spacing-body-sm)',
        'body-xs': 'var(--letter-spacing-body-xs)',
        'label-lg': 'var(--letter-spacing-label-lg)',
        'label-md': 'var(--letter-spacing-label-md)',
        'label-sm': 'var(--letter-spacing-label-sm)',
      },
      fontWeight: {
        'display-light': 'var(--font-weight-display-light)',
        'display-regular': 'var(--font-weight-display-regular)',
        'display-medium': 'var(--font-weight-display-medium)',
        'display-bold': 'var(--font-weight-display-bold)',
        'display-bold-condensed': 'var(--font-weight-display-bold-condensed)',
        'heading-light': 'var(--font-weight-heading-light)',
        'heading-regular': 'var(--font-weight-heading-regular)',
        'heading-medium': 'var(--font-weight-heading-medium)',
        'heading-bold': 'var(--font-weight-heading-bold)',
        'heading-bold-condensed': 'var(--font-weight-heading-bold-condensed)',
        'body-regular': 'var(--font-weight-body-regular)',
        'body-regular-italic': 'var(--font-weight-body-regular-italic)',
        'body-medium': 'var(--font-weight-body-medium)',
        'body-semibold': 'var(--font-weight-body-semibold)',
        'body-bold': 'var(--font-weight-body-bold)',
        'label-light': 'var(--font-weight-label-light)',
        'label-regular': 'var(--font-weight-label-regular)',
        'label-medium': 'var(--font-weight-label-medium)',
        'label-bold': 'var(--font-weight-label-bold)',
        'label-bold-condensed': 'var(--font-weight-label-bold-condensed)',
      },
      fontFamily: {
        display: 'var(--font-family-display)',
        'display-condensed': 'var(--font-family-display-condensed)',
        heading: 'var(--font-family-heading)',
        'heading-condensed': 'var(--font-family-heading-condensed)',
        'heading-serif': 'var(--font-family-heading-serif)',
        body: 'var(--font-family-body)',
        label: 'var(--font-family-label)',
        'label-condensed': 'var(--font-family-label-condensed)',
      },
      size: {
        'icon-xs': 'var(--size-icon-xs)',
        'icon-sm': 'var(--size-icon-sm)',
        'icon-md': 'var(--size-icon-md)',
        'icon-lg': 'var(--size-icon-lg)',
        'button-height-xs': 'var(--size-button-height-xs)',
        'button-height-sm': 'var(--size-button-height-sm)',
        'button-height-md': 'var(--size-button-height-md)',
        'button-height-lg': 'var(--size-button-height-lg)',
      },
      borderRadius: {
        none: 'var(--border-radius-none)',
        sm: 'var(--border-radius-sm)',
        base: 'var(--border-radius-base)',
        md: 'var(--border-radius-md)',
        lg: 'var(--border-radius-lg)',
        xl: 'var(--border-radius-xl)',
        '2xl': 'var(--border-radius-2xl)',
        '3xl': 'var(--border-radius-3xl)',
        '4xl': 'var(--border-radius-4xl)',
        '5xl': 'var(--border-radius-5xl)',
        full: 'var(--border-radius-full)',
      },
      borderWidth: {
        none: 'var(--border-width-none)',
        xthin: 'var(--border-width-xthin)',
        thin: 'var(--border-width-thin)',
        thick: 'var(--border-width-thick)',
        thicker: 'var(--border-width-thicker)',
        thickest: 'var(--border-width-thickest)',
        '3': '0.1875rem',
      },
    },
  },
  mode: 'jit',
  content: ['./src/**/*.{ts,tsx,js,jsx,mdx}'],
  darkMode: 'class',
  safelist: [
    'bg-bg-base-primary',
    'bg-bg-base-secondary',
    'bg-bg-base-tertiary',
    'bg-bg-base-quaternary',
    'bg-bg-base-brand-primary-tint',
    'bg-bg-base-brand-secondary-tint',
    'bg-bg-base-brand-tertiary-tint',
    'bg-bg-base-brand-quaternary-tint',
    'bg-bg-base-brand-quinary-tint',
    'bg-bg-base-brand-senary-tint',
    'bg-bg-base-brand-primary',
    'bg-bg-base-brand-tertiary',
    'bg-bg-base-brand-quarternary',
    'bg-bg-base-success',
    'bg-bg-base-warning',
    'bg-bg-base-destructive',
    'bg-bg-base-information',
    'bg-bg-base-alpha-overlay',
    'bg-bg-base-alpha-none',
    'bg-bg-base-alpha-low',
    'bg-bg-base-alpha-medium',
    'bg-bg-base-alpha-high',
    'bg-bg-badge-primary-default',
    'bg-bg-badge-primary-hover',
    'bg-bg-badge-secondary-default',
    'bg-bg-badge-secondary-hover',
    'bg-bg-badge-tertiary-default',
    'bg-bg-badge-tertiary-hover',
    'bg-bg-badge-outline-default',
    'bg-bg-badge-outline-hover',
    'bg-bg-button-primary-default',
    'bg-bg-button-primary-hover',
    'bg-bg-button-primary-active',
    'bg-bg-button-primary-disabled',
    'bg-bg-button-secondary-default',
    'bg-bg-button-secondary-hover',
    'bg-bg-button-secondary-active',
    'bg-bg-button-secondary-disabled',
    'bg-bg-button-tertiary-default',
    'bg-bg-button-tertiary-hover',
    'bg-bg-button-tertiary-active',
    'bg-bg-button-tertiary-disabled',
    'bg-bg-dataviz-dataviz-1',
    'bg-bg-dataviz-dataviz-2',
    'bg-bg-dataviz-dataviz-3',
    'bg-bg-dataviz-dataviz-4',
    'bg-bg-dataviz-dataviz-5',
    'bg-bg-dataviz-map-state',
    'bg-bg-dataviz-map-state-level-1',
    'bg-bg-dataviz-map-state-level-2',
    'bg-bg-dataviz-map-state-level-3',
    'bg-bg-dataviz-map-state-level-4',
    'bg-bg-dataviz-map-state-level-5',
    'bg-bg-dataviz-dataviz-6',
    'bg-bg-footer-default',
    'bg-bg-input-default',
    'bg-bg-input-focus',
    'bg-bg-input-hover',
    'bg-bg-input-disabled',
    'bg-bg-jumpnav-default',
    'bg-bg-link-filled-default',
    'bg-bg-link-filled-visited',
    'bg-bg-link-filled-hover',
    'bg-bg-link-filled-active',
    'bg-bg-logo-box',
    'bg-bg-logo-dog-ear',
    'bg-bg-logo-word-on-box',
    'bg-bg-logo-word-name',
    'bg-bg-menu-default',
    'bg-bg-menu-hover',
    'bg-bg-menu-active',
    'bg-bg-menu-selected',
    'bg-bg-navigation-default',
    'bg-bg-navigation-hover',
    'bg-bg-navigation-active',
    'bg-bg-navigation-selected',
    'bg-bg-navigation-expanded',
    'bg-bg-pagination-default',
    'bg-bg-pagination-hover',
    'bg-bg-pagination-active',
    'bg-bg-pagination-selected',
    'bg-bg-slider-default',
    'bg-bg-slider-active',
    'bg-bg-sonner-button-default',
    'bg-bg-sonner-button-hover',
    'bg-bg-sonner-button-active',
    'bg-bg-spotify-player-primary',
    'bg-bg-switch-default',
    'bg-bg-switch-selected',
    'bg-bg-tabs-default',
    'bg-bg-tabs-hover',
    'bg-bg-tabs-active',
    'bg-bg-tabs-selected',
    'bg-bg-toast-button-base-default',
    'bg-bg-toast-button-base-hover',
    'bg-bg-toast-button-base-active',
    'bg-bg-toast-button-destructive-default',
    'bg-bg-toast-button-destructive-hover',
    'bg-bg-toast-button-destructive-active',
    'bg-bg-toggle-default',
    'bg-bg-toggle-hover',
    'bg-bg-toggle-active',
    'bg-bg-toggle-selected',
    'bg-bg-toggle-disabled',
    'bg-text-base-primary',
    'bg-text-base-secondary',
    'bg-text-base-tertiary',
    'bg-text-base-quaternary',
    'bg-text-base-brand-primary',
    'bg-text-base-brand-secondary',
    'bg-text-base-brand-tertiary',
    'bg-text-base-brand-quaternary',
    'bg-text-base-title-brand-quarternary',
    'bg-text-base-success',
    'bg-text-base-warning',
    'bg-text-base-destructive',
    'bg-text-base-information',
    'bg-text-icon-primary',
    'bg-text-icon-secondary',
    'bg-text-icon-tertiary',
    'bg-text-icon-quaternary',
    'bg-text-icon-brand-primary',
    'bg-text-icon-brand-secondary',
    'bg-text-icon-brand-tertiary',
    'bg-text-icon-brand-quaternary',
    'bg-text-icon-success',
    'bg-text-icon-warning',
    'bg-text-icon-destructive',
    'bg-text-icon-information',
    'bg-text-badge-primary-base-default',
    'bg-text-badge-primary-base-hover',
    'bg-text-badge-primary-icon-default',
    'bg-text-badge-primary-icon-hover',
    'bg-text-badge-secondary-base-default',
    'bg-text-badge-secondary-base-hover',
    'bg-text-badge-secondary-icon-default',
    'bg-text-badge-secondary-icon-hover',
    'bg-text-badge-tertiary-base-default',
    'bg-text-badge-tertiary-base-hover',
    'bg-text-badge-tertiary-icon-default',
    'bg-text-badge-tertiary-icon-hover',
    'bg-text-badge-outline-base-default',
    'bg-text-badge-outline-base-hover',
    'bg-text-badge-outline-icon-default',
    'bg-text-badge-outline-icon-hover',
    'bg-text-button-primary-base-default',
    'bg-text-button-primary-base-hover',
    'bg-text-button-primary-base-active',
    'bg-text-button-primary-base-disabled',
    'bg-text-button-primary-icon-default',
    'bg-text-button-primary-icon-hover',
    'bg-text-button-primary-icon-active',
    'bg-text-button-primary-icon-disabled',
    'bg-text-button-secondary-base-default',
    'bg-text-button-secondary-base-hover',
    'bg-text-button-secondary-base-active',
    'bg-text-button-secondary-base-disabled',
    'bg-text-button-secondary-icon-default',
    'bg-text-button-secondary-icon-hover',
    'bg-text-button-secondary-icon-active',
    'bg-text-button-secondary-icon-disabled',
    'bg-text-button-tertiary-base-default',
    'bg-text-button-tertiary-base-hover',
    'bg-text-button-tertiary-base-active',
    'bg-text-button-tertiary-base-disabled',
    'bg-text-button-tertiary-icon-default',
    'bg-text-button-tertiary-icon-hover',
    'bg-text-button-tertiary-icon-active',
    'bg-text-button-tertiary-icon-disabled',
    'bg-text-dataviz-dataviz-1',
    'bg-text-dataviz-dataviz-2',
    'bg-text-dataviz-dataviz-3',
    'bg-text-dataviz-dataviz-4',
    'bg-text-dataviz-dataviz-5',
    'bg-text-dataviz-map-state-label',
    'bg-text-dataviz-map-state-label-outside',
    'bg-text-input-base-default',
    'bg-text-input-base-placeholder',
    'bg-text-input-base-hover',
    'bg-text-input-base-focus',
    'bg-text-input-base-selected',
    'bg-text-input-base-disabled',
    'bg-text-input-icon-default',
    'bg-text-input-icon-placeholder',
    'bg-text-input-icon-hover',
    'bg-text-input-icon-focus',
    'bg-text-input-icon-selected-alt',
    'bg-text-input-icon-disabled',
    'bg-text-link-default-base-default',
    'bg-text-link-default-base-visited',
    'bg-text-link-default-base-hover',
    'bg-text-link-default-base-active',
    'bg-text-link-default-icon-default',
    'bg-text-link-default-icon-visited',
    'bg-text-link-default-icon-hover',
    'bg-text-link-default-icon-active',
    'bg-text-link-filled-base-default',
    'bg-text-link-filled-base-visited',
    'bg-text-link-filled-base-hover',
    'bg-text-link-filled-base-active',
    'bg-text-link-filled-icon-default',
    'bg-text-link-filled-icon-visited',
    'bg-text-link-filled-icon-hover',
    'bg-text-link-filled-icon-active',
    'bg-text-link-footer-base-default',
    'bg-text-link-footer-base-visited',
    'bg-text-link-footer-base-hover',
    'bg-text-link-footer-base-active',
    'bg-text-link-nav-base-default',
    'bg-text-link-nav-base-visited',
    'bg-text-link-nav-base-hover',
    'bg-text-link-nav-base-active',
    'bg-text-menu-base-default',
    'bg-text-menu-base-hover',
    'bg-text-menu-base-active',
    'bg-text-menu-base-selected',
    'bg-text-navigation-base-default',
    'bg-text-navigation-base-featured',
    'bg-text-navigation-base-hover',
    'bg-text-navigation-base-active',
    'bg-text-navigation-icon-default',
    'bg-text-navigation-icon-featured',
    'bg-text-navigation-icon-hover',
    'bg-text-navigation-icon-active',
    'bg-text-navigation-item-base-default',
    'bg-text-navigation-item-base-visited',
    'bg-text-navigation-item-base-hover',
    'bg-text-navigation-item-base-active',
    'bg-text-pagination-base-default',
    'bg-text-pagination-base-hover',
    'bg-text-pagination-base-active',
    'bg-text-pagination-base-selected',
    'bg-text-pagination-icon-default',
    'bg-text-pagination-icon-hover',
    'bg-text-pagination-icon-active',
    'bg-text-slider-active',
    'bg-text-sonner-button-base-default',
    'bg-text-sonner-button-base-hover',
    'bg-text-sonner-button-base-active',
    'bg-text-spotify-player-primary',
    'bg-text-switch-default',
    'bg-text-tabs-base-default',
    'bg-text-tabs-base-hover',
    'bg-text-tabs-base-active',
    'bg-text-tabs-base-selected',
    'bg-text-tabs-icon-default',
    'bg-text-tabs-icon-hover',
    'bg-text-tabs-icon-active',
    'bg-text-tabs-icon-selected',
    'bg-text-toast-button-base-default',
    'bg-text-toast-button-base-hover',
    'bg-text-toast-button-base-active',
    'bg-text-toast-button-destructive-default',
    'bg-text-toast-button-destructive-hover',
    'bg-text-toast-button-destructive-active',
    'bg-text-toggle-base-default',
    'bg-text-toggle-base-hover',
    'bg-text-toggle-base-active',
    'bg-text-toggle-base-selected',
    'bg-text-toggle-base-disabled',
    'bg-text-toggle-icon-default',
    'bg-text-toggle-icon-hover',
    'bg-text-toggle-icon-active',
    'bg-text-toggle-icon-selected',
    'bg-text-toggle-icon-disabled',
    'bg-text-jumpnav-base-default',
    'bg-text-jumpnav-base-hover',
    'bg-text-jumpnav-base-active',
    'bg-border-base-primary',
    'bg-border-base-secondary',
    'bg-border-base-tertiary',
    'bg-border-base-quaternary',
    'bg-border-base-quinary',
    'bg-border-base-brand-primary',
    'bg-border-base-brand-tertiary',
    'bg-border-base-brand-tertiary-tint',
    'bg-border-base-brand-quaternary-tint',
    'bg-border-base-alpha-none',
    'bg-border-base-alpha-30',
    'bg-border-base-success',
    'bg-border-base-warning',
    'bg-border-base-destructive',
    'bg-border-base-information',
    'bg-border-badge-primary-default',
    'bg-border-badge-primary-hover',
    'bg-border-badge-secondary-default',
    'bg-border-badge-secondary-hover',
    'bg-border-badge-tertiary-default',
    'bg-border-badge-tertiary-hover',
    'bg-border-badge-outline-default',
    'bg-border-badge-outline-hover',
    'bg-border-button-primary-default',
    'bg-border-button-primary-hover',
    'bg-border-button-primary-active',
    'bg-border-button-primary-disabled',
    'bg-border-button-secondary-default',
    'bg-border-button-secondary-hover',
    'bg-border-button-secondary-active',
    'bg-border-button-secondary-disabled',
    'bg-border-button-tertiary-default',
    'bg-border-button-tertiary-hover',
    'bg-border-button-tertiary-active',
    'bg-border-button-tertiary-disabled',
    'bg-border-dataviz-dataviz-1',
    'bg-border-dataviz-dataviz-2',
    'bg-border-dataviz-dataviz-3',
    'bg-border-dataviz-dataviz-4',
    'bg-border-dataviz-dataviz-5',
    'bg-border-dataviz-map-state',
    'bg-border-dataviz-map-state-label-stroke',
    'bg-border-dataviz-map-state-label-line',
    'bg-border-focus-inner',
    'bg-border-focus-outer',
    'bg-border-input-default',
    'bg-border-input-hover',
    'bg-border-input-focus',
    'bg-border-input-selected',
    'bg-border-input-disabled',
    'bg-border-jumpnav-container',
    'bg-border-jumpnav-active',
    'bg-border-link-default',
    'bg-border-link-visited',
    'bg-border-link-hover',
    'bg-border-link-active',
    'bg-border-menu-default',
    'bg-border-menu-hover',
    'bg-border-menu-active',
    'bg-border-menu-selected',
    'bg-border-navigation-default',
    'bg-border-navigation-hover',
    'bg-border-navigation-active',
    'bg-border-navigation-selected',
    'bg-border-navigation-expanded',
    'bg-border-pagination-default',
    'bg-border-pagination-hover',
    'bg-border-pagination-selected',
    'bg-border-select-default',
    'bg-border-select-hover',
    'bg-border-select-active',
    'bg-border-select-disabled',
    'bg-border-slider-active',
    'bg-border-tabs-default',
    'bg-border-tabs-hover',
    'bg-border-tabs-active',
    'bg-border-tabs-selected',
    'bg-border-toast-button-base-default',
    'bg-border-toast-button-base-hover',
    'bg-border-toast-button-base-active',
    'bg-border-toast-button-destructive-default',
    'bg-border-toast-button-destructive-hover',
    'bg-border-toast-button-destructive-active',
    'bg-border-toggle-default',
    'bg-border-toggle-hover',
    'bg-border-toggle-active',
    'bg-border-toggle-selected',
    'bg-border-toggle-disabled',
    'text-bg-base-primary',
    'text-bg-base-secondary',
    'text-bg-base-tertiary',
    'text-bg-base-quaternary',
    'text-bg-base-brand-primary-tint',
    'text-bg-base-brand-secondary-tint',
    'text-bg-base-brand-tertiary-tint',
    'text-bg-base-brand-quaternary-tint',
    'text-bg-base-brand-quinary-tint',
    'text-bg-base-brand-senary-tint',
    'text-bg-base-brand-primary',
    'text-bg-base-brand-tertiary',
    'text-bg-base-brand-quarternary',
    'text-bg-base-success',
    'text-bg-base-warning',
    'text-bg-base-destructive',
    'text-bg-base-information',
    'text-bg-base-alpha-overlay',
    'text-bg-base-alpha-none',
    'text-bg-base-alpha-low',
    'text-bg-base-alpha-medium',
    'text-bg-base-alpha-high',
    'text-bg-badge-primary-default',
    'text-bg-badge-primary-hover',
    'text-bg-badge-secondary-default',
    'text-bg-badge-secondary-hover',
    'text-bg-badge-tertiary-default',
    'text-bg-badge-tertiary-hover',
    'text-bg-badge-outline-default',
    'text-bg-badge-outline-hover',
    'text-bg-button-primary-default',
    'text-bg-button-primary-hover',
    'text-bg-button-primary-active',
    'text-bg-button-primary-disabled',
    'text-bg-button-secondary-default',
    'text-bg-button-secondary-hover',
    'text-bg-button-secondary-active',
    'text-bg-button-secondary-disabled',
    'text-bg-button-tertiary-default',
    'text-bg-button-tertiary-hover',
    'text-bg-button-tertiary-active',
    'text-bg-button-tertiary-disabled',
    'text-bg-dataviz-dataviz-1',
    'text-bg-dataviz-dataviz-2',
    'text-bg-dataviz-dataviz-3',
    'text-bg-dataviz-dataviz-4',
    'text-bg-dataviz-dataviz-5',
    'text-bg-dataviz-map-state',
    'text-bg-dataviz-map-state-level-1',
    'text-bg-dataviz-map-state-level-2',
    'text-bg-dataviz-map-state-level-3',
    'text-bg-dataviz-map-state-level-4',
    'text-bg-dataviz-map-state-level-5',
    'text-bg-dataviz-dataviz-6',
    'text-bg-footer-default',
    'text-bg-input-default',
    'text-bg-input-focus',
    'text-bg-input-hover',
    'text-bg-input-disabled',
    'text-bg-jumpnav-default',
    'text-bg-link-filled-default',
    'text-bg-link-filled-visited',
    'text-bg-link-filled-hover',
    'text-bg-link-filled-active',
    'text-bg-logo-box',
    'text-bg-logo-dog-ear',
    'text-bg-logo-word-on-box',
    'text-bg-logo-word-name',
    'text-bg-menu-default',
    'text-bg-menu-hover',
    'text-bg-menu-active',
    'text-bg-menu-selected',
    'text-bg-navigation-default',
    'text-bg-navigation-hover',
    'text-bg-navigation-active',
    'text-bg-navigation-selected',
    'text-bg-navigation-expanded',
    'text-bg-pagination-default',
    'text-bg-pagination-hover',
    'text-bg-pagination-active',
    'text-bg-pagination-selected',
    'text-bg-slider-default',
    'text-bg-slider-active',
    'text-bg-sonner-button-default',
    'text-bg-sonner-button-hover',
    'text-bg-sonner-button-active',
    'text-bg-spotify-player-primary',
    'text-bg-switch-default',
    'text-bg-switch-selected',
    'text-bg-tabs-default',
    'text-bg-tabs-hover',
    'text-bg-tabs-active',
    'text-bg-tabs-selected',
    'text-bg-toast-button-base-default',
    'text-bg-toast-button-base-hover',
    'text-bg-toast-button-base-active',
    'text-bg-toast-button-destructive-default',
    'text-bg-toast-button-destructive-hover',
    'text-bg-toast-button-destructive-active',
    'text-bg-toggle-default',
    'text-bg-toggle-hover',
    'text-bg-toggle-active',
    'text-bg-toggle-selected',
    'text-bg-toggle-disabled',
    'text-text-base-primary',
    'text-text-base-secondary',
    'text-text-base-tertiary',
    'text-text-base-quaternary',
    'text-text-base-brand-primary',
    'text-text-base-brand-secondary',
    'text-text-base-brand-tertiary',
    'text-text-base-brand-quaternary',
    'text-text-base-title-brand-quarternary',
    'text-text-base-success',
    'text-text-base-warning',
    'text-text-base-destructive',
    'text-text-base-information',
    'text-text-icon-primary',
    'text-text-icon-secondary',
    'text-text-icon-tertiary',
    'text-text-icon-quaternary',
    'text-text-icon-brand-primary',
    'text-text-icon-brand-secondary',
    'text-text-icon-brand-tertiary',
    'text-text-icon-brand-quaternary',
    'text-text-icon-success',
    'text-text-icon-warning',
    'text-text-icon-destructive',
    'text-text-icon-information',
    'text-text-badge-primary-base-default',
    'text-text-badge-primary-base-hover',
    'text-text-badge-primary-icon-default',
    'text-text-badge-primary-icon-hover',
    'text-text-badge-secondary-base-default',
    'text-text-badge-secondary-base-hover',
    'text-text-badge-secondary-icon-default',
    'text-text-badge-secondary-icon-hover',
    'text-text-badge-tertiary-base-default',
    'text-text-badge-tertiary-base-hover',
    'text-text-badge-tertiary-icon-default',
    'text-text-badge-tertiary-icon-hover',
    'text-text-badge-outline-base-default',
    'text-text-badge-outline-base-hover',
    'text-text-badge-outline-icon-default',
    'text-text-badge-outline-icon-hover',
    'text-text-button-primary-base-default',
    'text-text-button-primary-base-hover',
    'text-text-button-primary-base-active',
    'text-text-button-primary-base-disabled',
    'text-text-button-primary-icon-default',
    'text-text-button-primary-icon-hover',
    'text-text-button-primary-icon-active',
    'text-text-button-primary-icon-disabled',
    'text-text-button-secondary-base-default',
    'text-text-button-secondary-base-hover',
    'text-text-button-secondary-base-active',
    'text-text-button-secondary-base-disabled',
    'text-text-button-secondary-icon-default',
    'text-text-button-secondary-icon-hover',
    'text-text-button-secondary-icon-active',
    'text-text-button-secondary-icon-disabled',
    'text-text-button-tertiary-base-default',
    'text-text-button-tertiary-base-hover',
    'text-text-button-tertiary-base-active',
    'text-text-button-tertiary-base-disabled',
    'text-text-button-tertiary-icon-default',
    'text-text-button-tertiary-icon-hover',
    'text-text-button-tertiary-icon-active',
    'text-text-button-tertiary-icon-disabled',
    'text-text-dataviz-dataviz-1',
    'text-text-dataviz-dataviz-2',
    'text-text-dataviz-dataviz-3',
    'text-text-dataviz-dataviz-4',
    'text-text-dataviz-dataviz-5',
    'text-text-dataviz-map-state-label',
    'text-text-dataviz-map-state-label-outside',
    'text-text-input-base-default',
    'text-text-input-base-placeholder',
    'text-text-input-base-hover',
    'text-text-input-base-focus',
    'text-text-input-base-selected',
    'text-text-input-base-disabled',
    'text-text-input-icon-default',
    'text-text-input-icon-placeholder',
    'text-text-input-icon-hover',
    'text-text-input-icon-focus',
    'text-text-input-icon-selected-alt',
    'text-text-input-icon-disabled',
    'text-text-link-default-base-default',
    'text-text-link-default-base-visited',
    'text-text-link-default-base-hover',
    'text-text-link-default-base-active',
    'text-text-link-default-icon-default',
    'text-text-link-default-icon-visited',
    'text-text-link-default-icon-hover',
    'text-text-link-default-icon-active',
    'text-text-link-filled-base-default',
    'text-text-link-filled-base-visited',
    'text-text-link-filled-base-hover',
    'text-text-link-filled-base-active',
    'text-text-link-filled-icon-default',
    'text-text-link-filled-icon-visited',
    'text-text-link-filled-icon-hover',
    'text-text-link-filled-icon-active',
    'text-text-link-footer-base-default',
    'text-text-link-footer-base-visited',
    'text-text-link-footer-base-hover',
    'text-text-link-footer-base-active',
    'text-text-link-nav-base-default',
    'text-text-link-nav-base-visited',
    'text-text-link-nav-base-hover',
    'text-text-link-nav-base-active',
    'text-text-menu-base-default',
    'text-text-menu-base-hover',
    'text-text-menu-base-active',
    'text-text-menu-base-selected',
    'text-text-navigation-base-default',
    'text-text-navigation-base-featured',
    'text-text-navigation-base-hover',
    'text-text-navigation-base-active',
    'text-text-navigation-icon-default',
    'text-text-navigation-icon-featured',
    'text-text-navigation-icon-hover',
    'text-text-navigation-icon-active',
    'text-text-navigation-item-base-default',
    'text-text-navigation-item-base-visited',
    'text-text-navigation-item-base-hover',
    'text-text-navigation-item-base-active',
    'text-text-pagination-base-default',
    'text-text-pagination-base-hover',
    'text-text-pagination-base-active',
    'text-text-pagination-base-selected',
    'text-text-pagination-icon-default',
    'text-text-pagination-icon-hover',
    'text-text-pagination-icon-active',
    'text-text-slider-active',
    'text-text-sonner-button-base-default',
    'text-text-sonner-button-base-hover',
    'text-text-sonner-button-base-active',
    'text-text-spotify-player-primary',
    'text-text-switch-default',
    'text-text-tabs-base-default',
    'text-text-tabs-base-hover',
    'text-text-tabs-base-active',
    'text-text-tabs-base-selected',
    'text-text-tabs-icon-default',
    'text-text-tabs-icon-hover',
    'text-text-tabs-icon-active',
    'text-text-tabs-icon-selected',
    'text-text-toast-button-base-default',
    'text-text-toast-button-base-hover',
    'text-text-toast-button-base-active',
    'text-text-toast-button-destructive-default',
    'text-text-toast-button-destructive-hover',
    'text-text-toast-button-destructive-active',
    'text-text-toggle-base-default',
    'text-text-toggle-base-hover',
    'text-text-toggle-base-active',
    'text-text-toggle-base-selected',
    'text-text-toggle-base-disabled',
    'text-text-toggle-icon-default',
    'text-text-toggle-icon-hover',
    'text-text-toggle-icon-active',
    'text-text-toggle-icon-selected',
    'text-text-toggle-icon-disabled',
    'text-text-jumpnav-base-default',
    'text-text-jumpnav-base-hover',
    'text-text-jumpnav-base-active',
    'text-border-base-primary',
    'text-border-base-secondary',
    'text-border-base-tertiary',
    'text-border-base-quaternary',
    'text-border-base-quinary',
    'text-border-base-brand-primary',
    'text-border-base-brand-tertiary',
    'text-border-base-brand-tertiary-tint',
    'text-border-base-brand-quaternary-tint',
    'text-border-base-alpha-none',
    'text-border-base-alpha-30',
    'text-border-base-success',
    'text-border-base-warning',
    'text-border-base-destructive',
    'text-border-base-information',
    'text-border-badge-primary-default',
    'text-border-badge-primary-hover',
    'text-border-badge-secondary-default',
    'text-border-badge-secondary-hover',
    'text-border-badge-tertiary-default',
    'text-border-badge-tertiary-hover',
    'text-border-badge-outline-default',
    'text-border-badge-outline-hover',
    'text-border-button-primary-default',
    'text-border-button-primary-hover',
    'text-border-button-primary-active',
    'text-border-button-primary-disabled',
    'text-border-button-secondary-default',
    'text-border-button-secondary-hover',
    'text-border-button-secondary-active',
    'text-border-button-secondary-disabled',
    'text-border-button-tertiary-default',
    'text-border-button-tertiary-hover',
    'text-border-button-tertiary-active',
    'text-border-button-tertiary-disabled',
    'text-border-dataviz-dataviz-1',
    'text-border-dataviz-dataviz-2',
    'text-border-dataviz-dataviz-3',
    'text-border-dataviz-dataviz-4',
    'text-border-dataviz-dataviz-5',
    'text-border-dataviz-map-state',
    'text-border-dataviz-map-state-label-stroke',
    'text-border-dataviz-map-state-label-line',
    'text-border-focus-inner',
    'text-border-focus-outer',
    'text-border-input-default',
    'text-border-input-hover',
    'text-border-input-focus',
    'text-border-input-selected',
    'text-border-input-disabled',
    'text-border-jumpnav-container',
    'text-border-jumpnav-active',
    'text-border-link-default',
    'text-border-link-visited',
    'text-border-link-hover',
    'text-border-link-active',
    'text-border-menu-default',
    'text-border-menu-hover',
    'text-border-menu-active',
    'text-border-menu-selected',
    'text-border-navigation-default',
    'text-border-navigation-hover',
    'text-border-navigation-active',
    'text-border-navigation-selected',
    'text-border-navigation-expanded',
    'text-border-pagination-default',
    'text-border-pagination-hover',
    'text-border-pagination-selected',
    'text-border-select-default',
    'text-border-select-hover',
    'text-border-select-active',
    'text-border-select-disabled',
    'text-border-slider-active',
    'text-border-tabs-default',
    'text-border-tabs-hover',
    'text-border-tabs-active',
    'text-border-tabs-selected',
    'text-border-toast-button-base-default',
    'text-border-toast-button-base-hover',
    'text-border-toast-button-base-active',
    'text-border-toast-button-destructive-default',
    'text-border-toast-button-destructive-hover',
    'text-border-toast-button-destructive-active',
    'text-border-toggle-default',
    'text-border-toggle-hover',
    'text-border-toggle-active',
    'text-border-toggle-selected',
    'text-border-toggle-disabled',
    'font-display',
    'font-display-condensed',
    'font-heading',
    'font-heading-condensed',
    'font-heading-serif',
    'font-body',
    'font-label',
    'font-label-condensed',
    'font-display-light',
    'font-display-regular',
    'font-display-medium',
    'font-display-bold',
    'font-display-bold-condensed',
    'font-heading-light',
    'font-heading-regular',
    'font-heading-medium',
    'font-heading-bold',
    'font-heading-bold-condensed',
    'font-body-regular',
    'font-body-regular-italic',
    'font-body-medium',
    'font-body-semibold',
    'font-body-bold',
    'font-label-light',
    'font-label-regular',
    'font-label-medium',
    'font-label-bold',
    'font-label-bold-condensed',
    'text-display-2xl',
    'text-display-xl',
    'text-display-lg',
    'text-display-md',
    'text-display-sm',
    'text-heading-xl',
    'text-heading-lg',
    'text-heading-md',
    'text-heading-sm',
    'text-heading-xs',
    'text-heading-xxs',
    'text-body-xl',
    'text-body-lg',
    'text-body-md',
    'text-body-sm',
    'text-body-xs',
    'text-label-lg',
    'text-label-md',
    'text-label-sm',
    'rounded-none',
    'rounded-sm',
    'rounded-base',
    'rounded-md',
    'rounded-lg',
    'rounded-xl',
    'rounded-2xl',
    'rounded-3xl',
    'rounded-4xl',
    'rounded-5xl',
    'rounded-full',
    'w-icon-xs',
    'w-icon-sm',
    'w-icon-md',
    'w-icon-lg',
    'w-button-height-xs',
    'w-button-height-sm',
    'w-button-height-md',
    'w-button-height-lg',
    'h-icon-xs',
    'h-icon-sm',
    'h-icon-md',
    'h-icon-lg',
    'h-button-height-xs',
    'h-button-height-sm',
    'h-button-height-md',
    'h-button-height-lg',
    'border-r-border-brands-politics',
    'border-r-border-brands-crime',
    'border-r-border-brands-religion',
    'border-r-border-brands-investigations',
    'border-r-border-brands-science',
    'border-r-border-brands-education',
    'border-r-border-brands-history',
    'border-r-border-brands-polling',
    'border-r-border-brands-health',
    'border-r-border-brands-markets',
    'border-r-border-brands-world',
    'border-r-border-brands-policy',
    'border-r-border-brands-defense',
    'border-r-border-brands-pennsylvania',
    'border-r-border-brands-public-affairs',
    'border-r-border-brands-book-culture',
    'bg-border-brands-politics',
    'bg-border-brands-crime',
    'bg-border-brands-religion',
    'bg-border-brands-investigations',
    'bg-border-brands-science',
    'bg-border-brands-education',
    'bg-border-brands-history',
    'bg-border-brands-polling',
    'bg-border-brands-health',
    'bg-border-brands-markets',
    'bg-border-brands-world',
    'bg-border-brands-policy',
    'bg-border-brands-defense',
    'bg-border-brands-pennsylvania',
    'bg-border-brands-public-affairs',
    'bg-border-brands-book-culture',
  ],
};
export default config;
